create table DogProfile (
	dogName VARCHAR(50),
	gender VARCHAR(50),
	age INT,
	breed VARCHAR(20),
	datePosted DATE,
	dogDesc VARCHAR(50)
);
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Erminia', 'Female', 7, 'Cockapoo', '7/9/2018', 'Kobus vardonii vardoni');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Lorelle', 'Female', 8, 'Cockapoo', '5/9/2018', 'Macropus eugenii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Fitzgerald', 'Male', 4, 'Jack Russell Terrier', '1/24/2018', 'Oryx gazella callotis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Eustacia', 'Female', 10, 'Poodle', '2/24/2019', 'Phalacrocorax carbo');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Aleece', 'Female', 6, 'Pit Bull', '4/12/2019', 'Morelia spilotes variegata');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Brinn', 'Female', 2, 'Terrier', '7/14/2018', 'Cygnus atratus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Zaneta', 'Female', 3, 'Poodle', '4/8/2019', 'Dendrocitta vagabunda');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gerard', 'Male', 4, 'Pomeranian', '5/13/2019', 'Phoenicopterus chilensis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Jena', 'Female', 9, 'Golden Retriever', '1/9/2019', 'Acridotheres tristis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Marabel', 'Female', 2, 'Goldendoodle', '10/18/2018', 'Lorythaixoides concolor');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Jessee', 'Male', 9, 'Boxer', '8/4/2018', 'Agkistrodon piscivorus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Putnem', 'Male', 5, 'Terrier', '10/5/2018', 'Libellula quadrimaculata');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Amitie', 'Female', 4, 'Beagle', '6/6/2018', 'Falco peregrinus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Nalani', 'Female', 8, 'Weiner Dog', '10/24/2018', 'Myrmecobius fasciatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gerhardine', 'Female', 8, 'Corgi', '1/9/2018', 'Castor fiber');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Basilio', 'Male', 7, 'Dachshund', '9/17/2018', 'Tenrec ecaudatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Luise', 'Female', 5, 'Beagle', '5/2/2018', 'Coluber constrictor foxii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Olag', 'Male', 2, 'Weiner Dog', '5/19/2018', 'Zenaida galapagoensis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Engracia', 'Female', 8, 'Chihuahua', '4/15/2019', 'Macaca mulatta');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Monique', 'Female', 5, 'Pomeranian', '3/5/2019', 'Phalacrocorax niger');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Judye', 'Female', 3, 'Goldendoodle', '1/27/2019', 'Francolinus leucoscepus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Zara', 'Female', 10, 'Poodle', '5/10/2019', 'Petaurus breviceps');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Carlynn', 'Female', 5, 'Terrier', '5/2/2018', 'Raphicerus campestris');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Axel', 'Male', 2, 'Pomeranian', '1/26/2019', 'Phasianus colchicus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Bevon', 'Male', 7, 'Terrier', '5/11/2018', 'Cyrtodactylus louisiadensis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Valentia', 'Female', 10, 'Pug', '2/16/2019', 'Haliaetus vocifer');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Elbertina', 'Female', 4, 'Pug', '7/17/2018', 'Conolophus subcristatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Sylvester', 'Male', 7, 'Boxer', '4/28/2019', 'Kobus defassa');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Rinaldo', 'Male', 2, 'Pomeranian', '5/13/2018', 'Spermophilus richardsonii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gerick', 'Male', 6, 'Terrier', '6/30/2018', 'Butorides striatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gasparo', 'Male', 4, 'Pomeranian', '5/18/2018', 'Sarcophilus harrisii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Daria', 'Female', 1, 'Dalmatian', '5/14/2018', 'Theropithecus gelada');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Roselia', 'Female', 5, 'Dalmatian', '5/13/2018', 'Bucephala clangula');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gardie', 'Male', 5, 'Weiner Dog', '3/29/2018', 'Francolinus swainsonii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Ferdie', 'Male', 2, 'Corgi', '9/11/2018', 'Marmota caligata');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Erasmus', 'Male', 5, 'Boxer', '3/16/2019', 'Creagrus furcatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Seamus', 'Male', 8, 'Dalmatian', '8/2/2018', 'unavailable');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Joan', 'Female', 5, 'Chihuahua', '2/12/2019', 'Lorythaixoides concolor');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Eulalie', 'Female', 4, 'Pomeranian', '2/5/2018', 'Pavo cristatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Donall', 'Male', 5, 'Pug', '1/20/2018', 'Myiarchus tuberculifer');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Kyla', 'Female', 1, 'Pit Bull', '11/4/2018', 'Larus dominicanus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Roanne', 'Female', 10, 'Dalmatian', '4/11/2018', 'Gyps bengalensis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Bartolomeo', 'Male', 7, 'Pomeranian', '1/7/2019', 'Parus atricapillus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Adriaens', 'Female', 10, 'Pit Bull', '11/11/2018', 'Ephippiorhynchus mycteria');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Claudio', 'Male', 7, 'Chihuahua', '11/1/2018', 'Spermophilus armatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Fons', 'Male', 2, 'Weiner Dog', '2/1/2018', 'Canis aureus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('L;urette', 'Female', 6, 'Corgi', '10/10/2018', 'Papio cynocephalus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Jaquenetta', 'Female', 1, 'Goldendoodle', '3/23/2018', 'Thylogale stigmatica');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Lurlene', 'Female', 2, 'Beagle', '3/24/2019', 'Lama glama');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Karine', 'Female', 1, 'Golden Retriever', '4/4/2018', 'Irania gutteralis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Arney', 'Male', 10, 'Chihuahua', '5/3/2019', 'Drymarchon corias couperi');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Bernie', 'Female', 2, 'Chihuahua', '3/25/2018', 'Casmerodius albus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gustav', 'Male', 2, 'Poodle', '1/7/2019', 'unavailable');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Renata', 'Female', 10, 'Terrier', '4/1/2019', 'Cebus apella');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Rennie', 'Female', 2, 'German Shepherd', '3/2/2018', 'Casmerodius albus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Phineas', 'Male', 3, 'Boxer', '5/24/2019', 'Eudromia elegans');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Templeton', 'Male', 2, 'Cockapoo', '3/9/2019', 'Chlamydosaurus kingii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Bailey', 'Male', 4, 'Cockapoo', '11/4/2018', 'Trichosurus vulpecula');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Saxe', 'Male', 4, 'Pomeranian', '7/21/2018', 'Oreotragus oreotragus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Erminia', 'Female', 1, 'Beagle', '4/18/2019', 'Galago crassicaudataus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Alfy', 'Female', 6, 'Golden Retriever', '4/17/2019', 'Phascolarctos cinereus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Adora', 'Female', 7, 'Jack Russell Terrier', '6/23/2018', 'unavailable');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Riley', 'Male', 7, 'Golden Retriever', '2/3/2018', 'Tadorna tadorna');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Leena', 'Female', 4, 'Dalmatian', '6/25/2018', 'Threskionis aethiopicus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Abram', 'Male', 10, 'Boxer', '7/17/2018', 'Eudyptula minor');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Ced', 'Male', 2, 'Corgi', '10/7/2018', 'Sarcophilus harrisii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Brigit', 'Female', 5, 'Goldendoodle', '9/6/2018', 'Ciconia episcopus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Valerie', 'Female', 1, 'Pomeranian', '12/15/2018', 'Hippotragus equinus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Kalle', 'Male', 7, 'Boxer', '3/13/2019', 'Callipepla gambelii');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Emily', 'Female', 5, 'Jack Russell Terrier', '2/4/2019', 'Taxidea taxus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Toddie', 'Male', 8, 'Pit Bull', '5/1/2018', 'Gyps bengalensis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Joshua', 'Male', 10, 'German Shepherd', '3/3/2019', 'Estrilda erythronotos');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Rainer', 'Male', 2, 'Dalmatian', '9/24/2018', 'Funambulus pennati');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Rhys', 'Male', 8, 'German Shepherd', '4/26/2018', 'Papio ursinus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Dore', 'Male', 6, 'Terrier', '4/23/2019', 'Coracias caudata');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Kirsti', 'Female', 3, 'Corgi', '1/3/2019', 'Lamprotornis chalybaeus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Adamo', 'Male', 6, 'Jack Russell Terrier', '7/6/2018', 'Bettongia penicillata');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Huberto', 'Male', 5, 'Goldendoodle', '6/29/2018', 'Seiurus aurocapillus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Ginni', 'Female', 10, 'Goldendoodle', '11/18/2018', 'Corythornis cristata');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Jard', 'Male', 7, 'Pug', '5/24/2019', 'Canis dingo');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Gerrie', 'Female', 9, 'Dachshund', '2/19/2019', 'Tauraco porphyrelophus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Catherine', 'Female', 5, 'Goldendoodle', '5/23/2019', 'Leprocaulinus vipera');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Ransell', 'Male', 5, 'Dalmatian', '9/21/2018', 'Sciurus vulgaris');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Link', 'Male', 10, 'Boxer', '11/1/2018', 'Choloepus hoffmani');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Dorothy', 'Female', 9, 'Dachshund', '11/4/2018', 'Porphyrio porphyrio');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Lamond', 'Male', 6, 'German Shepherd', '3/5/2018', 'Bubalornis niger');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Giffie', 'Male', 6, 'Golden Retriever', '2/21/2018', 'Macaca mulatta');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Damara', 'Female', 5, 'Pit Bull', '3/17/2019', 'Castor fiber');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Loralie', 'Female', 1, 'Weiner Dog', '12/27/2018', 'Pteronura brasiliensis');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Abigael', 'Female', 10, 'Corgi', '2/23/2018', 'Ara chloroptera');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Janek', 'Male', 4, 'Jack Russell Terrier', '8/7/2018', 'Mycteria leucocephala');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Culley', 'Male', 3, 'Corgi', '2/23/2019', 'Varanus salvator');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Lorrin', 'Female', 8, 'Dachshund', '6/16/2018', 'Zalophus californicus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Darelle', 'Female', 8, 'Chihuahua', '7/5/2018', 'Corvus albus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Editha', 'Female', 7, 'Pug', '4/12/2019', 'Rangifer tarandus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Corny', 'Female', 3, 'Corgi', '4/18/2019', 'Laniaurius atrococcineus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Carmen', 'Female', 5, 'Pug', '11/24/2018', 'Lybius torquatus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Urson', 'Male', 8, 'German Shepherd', '1/23/2019', 'Redunca redunca');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Justen', 'Male', 4, 'Pug', '12/2/2018', 'Lepus arcticus');
insert into DogProfile (dogName, gender, age, breed, datePosted, dogDesc) values ('Klemens', 'Male', 2, 'Poodle', '11/14/2018', 'Mephitis mephitis');
