insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'taldgate0', 'Tern, white-winged black', 'Yellow', 'Chlidonias leucopterus', '1/18/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'lbrixey1', 'Gray duiker', 'Puce', 'Sylvicapra grimma', '4/7/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'sfarryan2', 'Bat, madagascar fruit', 'Teal', 'Pteropus rufus', '11/21/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'ttilson3', 'White-throated kingfisher', 'Aquamarine', 'Halcyon smyrnesis', '3/16/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'klope4', 'Jackal, golden', 'Goldenrod', 'Canis aureus', '12/17/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'sattwool5', 'Green vine snake', 'Violet', 'Oxybelis fulgidus', '2/21/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'uwoffenden6', 'Ant (unidentified)', 'Maroon', 'unavailable', '11/21/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'sthackray7', 'African snake (unidentified)', 'Yellow', 'unavailable', '1/11/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'rloveard8', 'Gulls (unidentified)', 'Blue', 'Larus sp.', '5/1/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'adecaroli9', 'Lesser masked weaver', 'Indigo', 'Ploceus intermedius', '8/19/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'hhateleya', 'Cockatoo, slender-billed', 'Goldenrod', 'Cacatua tenuirostris', '7/5/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'owiddocksb', 'Grouse, greater sage', 'Khaki', 'Centrocercus urophasianus', '12/12/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'dnibloec', 'Monitor, water', 'Purple', 'Varanus salvator', '7/21/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'mamsdend', 'Griffon vulture', 'Aquamarine', 'Gyps fulvus', '9/14/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'bbovise', 'Sage grouse', 'Pink', 'Centrocercus urophasianus', '3/27/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'tmilwardf', 'Cockatoo, red-tailed', 'Blue', 'Calyptorhynchus magnificus', '7/4/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'wdemattiag', 'Goose, egyptian', 'Aquamarine', 'Alopochen aegyptiacus', '4/6/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'mweaverh', 'Sambar', 'Orange', 'Cervus unicolor', '3/23/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'jblackleechi', 'Kite, black', 'Fuscia', 'Milvus migrans', '6/9/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'rdaxj', 'House sparrow', 'Violet', 'Passer domesticus', '7/17/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'rdallicoatk', 'Golden jackal', 'Khaki', 'Canis aureus', '5/29/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'fmertonl', 'Red-billed toucan', 'Aquamarine', 'Ramphastos tucanus', '2/5/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'tmeenehanm', 'Chacma baboon', 'Green', 'Papio ursinus', '1/23/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'lgilliesn', 'Chameleon (unidentified)', 'Violet', 'Chamaelo sp.', '2/10/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'ltomankiewiczo', 'Paddy heron (unidentified)', 'Green', 'unavailable', '12/10/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'rtortisp', 'Bushbuck', 'Khaki', 'Tragelaphus scriptus', '2/24/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'galmanq', 'Dragon, frilled', 'Indigo', 'Chlamydosaurus kingii', '7/27/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'kbywayr', 'Frilled lizard', 'Violet', 'Chlamydosaurus kingii', '2/8/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'bpookes', 'Possum, western pygmy', 'Puce', 'Cercatetus concinnus', '5/5/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'rwellst', 'Duck, blue', 'Goldenrod', 'Hymenolaimus malacorhynchus', '1/24/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'dhovieu', 'Phalarope, northern', 'Goldenrod', 'Phalaropus lobatus', '9/15/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'afleischerv', 'Coatimundi, ring-tailed', 'Violet', 'Nasua nasua', '2/1/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'dmccutcheonw', 'Common waterbuck', 'Orange', 'Kobus defassa', '7/11/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'tskarinx', 'Fox, arctic', 'Khaki', 'Alopex lagopus', '5/25/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'sgilhouleyy', 'Bustard, stanley', 'Fuscia', 'Neotis denhami', '6/29/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'psandemanz', 'Pelican, brown', 'Goldenrod', 'Pelecanus occidentalis', '3/15/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'mjallin10', 'Snake, racer', 'Goldenrod', 'Coluber constrictor', '1/18/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'choble11', 'White-headed vulture', 'Indigo', 'Aegypius occipitalis', '4/4/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'lroaf12', 'Red hartebeest', 'Green', 'Alcelaphus buselaphus caama', '1/14/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'hosorio13', 'Frog (unidentified)', 'Turquoise', 'Rana sp.', '7/30/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'smcrobbie14', 'Red-breasted nuthatch', 'Pink', 'Sitta canadensis', '9/27/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'vmaruszewski15', 'Fowl, helmeted guinea', 'Turquoise', 'Numida meleagris', '2/4/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'asummergill16', 'Stork, yellow-billed', 'Violet', 'Mycteria ibis', '10/8/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'jtrencher17', 'Mouse, four-striped grass', 'Mauv', 'Rhabdomys pumilio', '2/25/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'rafonso18', 'Asian openbill', 'Purple', 'Anastomus oscitans', '6/2/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'keaston19', 'South American sea lion', 'Indigo', 'Otaria flavescens', '2/12/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'sedmondson1a', 'Toucan, red-billed', 'Khaki', 'Ramphastos tucanus', '10/30/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'ddallimore1b', 'Red-capped cardinal', 'Goldenrod', 'Paroaria gularis', '11/8/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'ushortell1c', 'Cockatoo, slender-billed', 'Orange', 'Cacatua tenuirostris', '3/15/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'thaborn1d', 'Parakeet, rose-ringed', 'Yellow', 'Psittacula krameri', '12/26/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'jparrett1e', 'Asian red fox', 'Teal', 'Vulpes vulpes', '1/9/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'llille1f', 'Red squirrel', 'Orange', 'Tamiasciurus hudsonicus', '8/17/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'amerredy1g', 'Jackal, golden', 'Aquamarine', 'Canis aureus', '6/10/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'ttohill1h', 'Yellow-crowned night heron', 'Green', 'Nyctanassa violacea', '4/5/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'tduffy1i', 'Vulture, king', 'Blue', 'Sarcorhamphus papa', '3/13/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'asallier1j', 'Striped skunk', 'Puce', 'Mephitis mephitis', '9/28/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'gnollet1k', 'Arctic fox', 'Pink', 'Alopex lagopus', '12/11/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'rlamartine1l', 'Grizzly bear', 'Teal', 'Ursus arctos', '6/25/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'pravillas1m', 'Cat, tiger', 'Aquamarine', 'Dasyurus maculatus', '11/22/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'aaulds1n', 'Roseate cockatoo', 'Purple', 'Eolophus roseicapillus', '8/22/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'aphonix1o', 'Plover, blacksmith', 'Turquoise', 'Vanellus armatus', '6/13/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'theam1p', 'Kudu, greater', 'Maroon', 'Tragelaphus strepsiceros', '11/12/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'esearby1q', 'Ringtail cat', 'Indigo', 'Bassariscus astutus', '7/4/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'ghovee1r', 'Mountain goat', 'Turquoise', 'Oreamnos americanus', '7/30/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'jshwalbe1s', 'Seal, northern fur', 'Goldenrod', 'Callorhinus ursinus', '7/23/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'gmargetson1t', 'Painted stork', 'Crimson', 'Mycteria leucocephala', '7/30/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'aabbet1u', 'Cat, european wild', 'Green', 'Felis silvestris lybica', '7/30/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'aosborn1v', 'Native cat', 'Green', 'Dasyurus viverrinus', '2/25/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'jwitty1w', 'Paddy heron (unidentified)', 'Indigo', 'unavailable', '5/16/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'gmedendorp1x', 'Defassa waterbuck', 'Pink', 'Kobus defassa', '3/30/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'ssterling1y', 'Raccoon, common', 'Mauv', 'Procyon lotor', '12/22/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'drosenfelt1z', 'Kangaroo, eastern grey', 'Yellow', 'Macropus giganteus', '1/13/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'jborzone20', 'Glider, sugar', 'Puce', 'Petaurus breviceps', '11/1/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'iepperson21', 'Viper, egyptian', 'Blue', 'Naja haje', '11/4/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'cduligal22', 'Mexican boa', 'Aquamarine', 'Boa constrictor mexicana', '2/16/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'pluquet23', 'Iguana, common green', 'Maroon', 'Iguana iguana', '1/6/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'cjimpson24', 'Emerald green tree boa', 'Yellow', 'Boa caninus', '10/12/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'gbasilio25', 'Dove, laughing', 'Yellow', 'Streptopelia senegalensis', '6/30/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'jklauber26', 'Quail, gambel''s', 'Yellow', 'Callipepla gambelii', '10/29/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'hgusticke27', 'Miner''s cat', 'Maroon', 'Bassariscus astutus', '10/16/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'fmuckersie28', 'American badger', 'Green', 'Taxidea taxus', '12/24/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'sduckering29', 'Lion, california sea', 'Maroon', 'Zalophus californicus', '8/17/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'rkelemen2a', 'Crested bunting', 'Crimson', 'Melophus lathami', '2/16/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (2, 'jodyvoy2b', 'Lizard, mexican beaded', 'Indigo', 'Heloderma horridum', '1/25/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'emellings2c', 'Finch, common melba', 'Khaki', 'Pytilia melba', '1/12/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'vganford2d', 'Brown antechinus', 'Orange', 'Antechinus flavipes', '8/27/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'egrimwade2e', 'Bear, black', 'Turquoise', 'Ursus americanus', '5/14/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'kgatley2f', 'Whale, baleen', 'Aquamarine', 'Eubalaena australis', '9/15/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'tcoomber2g', 'Steller sea lion', 'Teal', 'Eumetopias jubatus', '1/3/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'cshervil2h', 'Bottle-nose dolphin', 'Green', 'Tursiops truncatus', '1/1/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'astarzaker2i', 'Tiger cat', 'Turquoise', 'Dasyurus maculatus', '10/3/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'mlille2j', 'Heron, yellow-crowned night', 'Yellow', 'Nyctanassa violacea', '1/16/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'mcoils2k', 'Paddy heron (unidentified)', 'Orange', 'unavailable', '6/28/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (4, 'jlown2l', 'Shelduck, common', 'Teal', 'Tadorna tadorna', '1/7/2019');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'upage2m', 'Sparrow, rufous-collared', 'Orange', 'Zonotrichia capensis', '4/20/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'jburchill2n', 'Waxbill, violet-eared', 'Yellow', 'Uraeginthus granatina', '1/20/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (5, 'lbengtsson2o', 'Gull, dusky', 'Turquoise', 'Larus fuliginosus', '3/9/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (3, 'rover2p', 'Eagle, crowned', 'Violet', 'Spizaetus coronatus', '1/3/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'ehoudhury2q', 'Indian star tortoise', 'Mauv', 'Geochelone elegans', '11/22/2018');
insert into DogProfile (unid, dogName, gender, dogDesc, breed, datePosted) values (1, 'pmckellar2r', 'Jacana, african', 'Turquoise', 'Actophilornis africanus', '1/5/2019');
